import type { Metadata } from "next";
import { Montserrat, Inter } from "next/font/google";
import { Header, Footer } from "@/components/layout/Layouts";
import "./globals.css";

const headerFont = Montserrat({
  variable: "--font-header",
  subsets: ["latin"],
});

const bodyFont = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${headerFont.variable} ${bodyFont.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
